#!/bin/sh

python3 $(pwd)/tools/format_file.py $(pwd)/include/
python3 $(pwd)/tools/format_file.py $(pwd)/src/
python3 $(pwd)/tools/format_file.py $(pwd)/test/

python3 $(pwd)/tools/format_code.py $(pwd)/include/
python3 $(pwd)/tools/format_code.py $(pwd)/src/
python3 $(pwd)/tools/format_code.py $(pwd)/test/
