name: code scan

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check_pull_request:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: pip install chardet

      - run: sudo apt-get install clang-format-14
        
      - run: ./tools/format

      - run: git diff --exit-code ./include
      - run: git diff --exit-code ./src
      - run: git diff --exit-code ./test
