name: static code scan

on:
  pull_request:
    branches: [ "main" ]

jobs:
  scan_linux:
    name: Scan On Linux
    runs-on: ubuntu-latest
    steps:
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0

  scan_windows:
    name: Scan On Windows
    runs-on: windows-latest
    steps:
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
